export default [
  { "name": "Accenteur à gorge noire", "href": "accenteur.a.gorge.noire" },
  { "name": "Accenteur alpin", "href": "accenteur.alpin" },
  { "name": "Accenteur brun", "href": "accenteur.brun" },
  { "name": "Accenteur de l'Himalaya", "href": "accenteur.de.l.himalaya" },
  { "name": "Accenteur de Radde", "href": "accenteur.de.radde" },
  { "name": "Accenteur montanelle", "href": "accenteur.montanelle" },
  { "name": "Accenteur mouchet", "href": "accenteur.mouchet" },
  { "name": "Agrobate roux", "href": "agrobate.roux" },
  { "name": "Aigle botté", "href": "aigle.botte" },
  { "name": "Aigle criard", "href": "aigle.criard" },
  { "name": "Aigle de Bonelli", "href": "aigle.de.bonelli" },
  { "name": "Aigle des steppes", "href": "aigle.des.steppes" },
  { "name": "Aigle ibérique", "href": "aigle.iberique" },
  { "name": "Aigle impérial", "href": "aigle.imperial" },
  { "name": "Aigle pomarin", "href": "aigle.pomarin" },
  { "name": "Aigle ravisseur", "href": "aigle.ravisseur" },
  { "name": "Aigle royal", "href": "aigle.royal" },
  { "name": "Aigrette bleue", "href": "aigrette.bleue" },
  { "name": "Aigrette des récifs", "href": "aigrette.des.recifs" },
  { "name": "Aigrette garzette", "href": "aigrette.garzette" },
  { "name": "Aigrette neigeuse", "href": "aigrette.neigeuse" },
  { "name": "Aigrette tricolore", "href": "aigrette.tricolore" },
  { "name": "Albatros à nez jaune", "href": "albatros.a.nez.jaune" },
  { "name": "Albatros à sourcils noirs", "href": "albatros.a.sourcils.noirs" },
  { "name": "Albatros hurleur", "href": "albatros.hurleur" },
  { "name": "Alouette bilophe", "href": "alouette.bilophe" },
  { "name": "Alouette calandre", "href": "alouette.calandre" },
  { "name": "Alouette calandrelle", "href": "alouette.calandrelle" },
  { "name": "Alouette de Mongolie", "href": "alouette.de.mongolie" },
  { "name": "Alouette des champs", "href": "alouette.des.champs" },
  { "name": "Alouette haussecol", "href": "alouette.haussecol" },
  { "name": "Alouette leucoptère", "href": "alouette.leucoptere" },
  { "name": "Alouette lulu", "href": "alouette.lulu" },
  { "name": "Alouette monticole", "href": "alouette.monticole" },
  { "name": "Alouette nègre", "href": "alouette.negre" },
  { "name": "Alouette pispolette", "href": "alouette.pispolette" },
  { "name": "Alouette raytal", "href": "alouette.raytal" },
  { "name": "Ammomane élégante", "href": "ammomane.elegante" },
  { "name": "Ammomane isabelline", "href": "ammomane.isabelline" },
  { "name": "Anhinga d'Afrique", "href": "anhinga.d.afrique" },
  { "name": "Arlequin plongeur", "href": "arlequin.plongeur" },
  { "name": "Astrild à joues orange", "href": "astrild.a.joues.orange" },
  { "name": "Astrild cendré", "href": "astrild.cendre" },
  { "name": "Astrild ondulé", "href": "astrild.ondule" },
  { "name": "Autour des palombes", "href": "autour.des.palombes" },
  { "name": "Autour sombre", "href": "autour.sombre" },
  { "name": "Avocette d'Amérique", "href": "avocette.d.amerique" },
  { "name": "Avocette élégante", "href": "avocette.elegante" },
  { "name": "Balbuzard pêcheur", "href": "balbuzard.pecheur" },
  { "name": "Barge à queue noire", "href": "barge.a.queue.noire" },
  { "name": "Barge hudsonienne", "href": "barge.hudsonienne" },
  { "name": "Barge rousse", "href": "barge.rousse" },
  { "name": "Bartramie des champs", "href": "bartramie.des.champs" },
  { "name": "Bec-croisé bifascié", "href": "bec-croise.bifascie" },
  { "name": "Bec-croisé d'Ecosse", "href": "bec-croise.d.ecosse" },
  { "name": "Bec-croisé des sapins", "href": "bec-croise.des.sapins" },
  { "name": "Bec-croisé perroquet", "href": "bec-croise.perroquet" },
  { "name": "Bec-en-ciseaux d'Afrique", "href": "bec-en-ciseaux.d.afrique" },
  { "name": "Bécasse d'Amérique", "href": "becasse.d.amerique" },
  { "name": "Bécasse des bois", "href": "becasse.des.bois" },
  { "name": "Bécasseau à cou roux", "href": "becasseau.a.cou.roux" },
  { "name": "Bécasseau à échasses", "href": "becasseau.a.echasses" },
  { "name": "Bécasseau à longs doigts", "href": "becasseau.a.longs.doigts" },
  { "name": "Bécasseau à queue pointue", "href": "becasseau.a.queue.pointue" },
  { "name": "Bécasseau cocorli", "href": "becasseau.cocorli" },
  { "name": "Bécasseau d'Alaska", "href": "becasseau.d.alaska" },
  { "name": "Bécasseau de Baird", "href": "becasseau.de.baird" },
  { "name": "Bécasseau de Bonaparte", "href": "becasseau.de.bonaparte" },
  { "name": "Bécasseau de l'Anadyr", "href": "becasseau.de.l.anadyr" },
  { "name": "Bécasseau de Temminck", "href": "becasseau.de.temminck" },
  { "name": "Bécasseau falcinelle", "href": "becasseau.falcinelle" },
  { "name": "Bécasseau maubèche", "href": "becasseau.maubeche" },
  { "name": "Bécasseau minuscule", "href": "becasseau.minuscule" },
  { "name": "Bécasseau minute", "href": "becasseau.minute" },
  { "name": "Bécasseau rousset", "href": "becasseau.rousset" },
  { "name": "Bécasseau sanderling", "href": "becasseau.sanderling" },
  { "name": "Bécasseau semipalmé", "href": "becasseau.semipalme" },
  { "name": "Bécasseau spatule", "href": "becasseau.spatule" },
  { "name": "Bécasseau tacheté", "href": "becasseau.tachete" },
  { "name": "Bécasseau variable", "href": "becasseau.variable" },
  { "name": "Bécasseau violet", "href": "becasseau.violet" },
  { "name": "Bécassin à bec court", "href": "becassin.a.bec.court" },
  { "name": "Bécassin à long bec", "href": "becassin.a.long.bec" },
  { "name": "Bécassine à queue pointue", "href": "becassine.a.queue.pointue" },
  { "name": "Bécassine de Swinhoe", "href": "becassine.de.swinhoe" },
  { "name": "Bécassine de Wilson", "href": "becassine.de.wilson" },
  { "name": "Bécassine des marais", "href": "becassine.des.marais" },
  { "name": "Bécassine double", "href": "becassine.double" },
  { "name": "Bécassine solitaire", "href": "becassine.solitaire" },
  { "name": "Bécassine sourde", "href": "becassine.sourde" },
  { "name": "Bengali rouge", "href": "bengali.rouge" },
  { "name": "Bergeronnette citrine", "href": "bergeronnette.citrine" },
  { "name": "Bergeronnette de forêt", "href": "bergeronnette.de.foret" },
  {
    "name": "Bergeronnette des ruisseaux",
    "href": "bergeronnette.des.ruisseaux"
  },
  { "name": "Bergeronnette grise", "href": "bergeronnette.grise" },
  { "name": "Bergeronnette printanière", "href": "bergeronnette.printaniere" },
  { "name": "Bernache à cou roux", "href": "bernache.a.cou.roux" },
  { "name": "Bernache cravant", "href": "bernache.cravant" },
  { "name": "Bernache de Hutchins", "href": "bernache.de.hutchins" },
  { "name": "Bernache du Canada", "href": "bernache.du.canada" },
  { "name": "Bernache nonnette", "href": "bernache.nonnette" },
  { "name": "Bihoreau gris", "href": "bihoreau.gris" },
  { "name": "Bihoreau violacé", "href": "bihoreau.violace" },
  { "name": "Blongios de Sturm", "href": "blongios.de.sturm" },
  { "name": "Blongios mandchou", "href": "blongios.mandchou" },
  { "name": "Blongios nain", "href": "blongios.nain" },
  { "name": "Bondrée apivore", "href": "bondree.apivore" },
  { "name": "Bondrée orientale", "href": "bondree.orientale" },
  { "name": "Bouscarle de Cetti", "href": "bouscarle.de.cetti" },
  { "name": "Bouscarle de Taczanowski", "href": "bouscarle.de.taczanowski" },
  { "name": "Bouvreuil des Açores", "href": "bouvreuil.des.acores" },
  { "name": "Bouvreuil pivoine", "href": "bouvreuil.pivoine" },
  { "name": "Bruant à calotte blanche", "href": "bruant.a.calotte.blanche" },
  { "name": "Bruant à cou gris", "href": "bruant.a.cou.gris" },
  { "name": "Bruant à couronne blanche", "href": "bruant.a.couronne.blanche" },
  { "name": "Bruant à gorge blanche", "href": "bruant.a.gorge.blanche" },
  { "name": "Bruant à joues marron", "href": "bruant.a.joues.marron" },
  { "name": "Bruant à longue queue", "href": "bruant.a.longue.queue" },
  { "name": "Bruant à oreillons", "href": "bruant.a.oreillons" },
  { "name": "Bruant à sourcils jaunes", "href": "bruant.a.sourcils.jaunes" },
  { "name": "Bruant à tête rousse", "href": "bruant.a.tete.rousse" },
  { "name": "Bruant auréole", "href": "bruant.aureole" },
  { "name": "Bruant cendré", "href": "bruant.cendre" },
  { "name": "Bruant cendrillard", "href": "bruant.cendrillard" },
  { "name": "Bruant chanteur", "href": "bruant.chanteur" },
  { "name": "Bruant de Godlewski", "href": "bruant.de.godlewski" },
  { "name": "Bruant de Lincoln", "href": "bruant.de.lincoln" },
  { "name": "Bruant de Pallas", "href": "bruant.de.pallas" },
  { "name": "Bruant de Stewart", "href": "bruant.de.stewart" },
  { "name": "Bruant des neiges", "href": "bruant.des.neiges" },
  { "name": "Bruant des prés", "href": "bruant.des.pres" },
  { "name": "Bruant des roseaux", "href": "bruant.des.roseaux" },
  { "name": "Bruant du Sahara", "href": "bruant.du.sahara" },
  { "name": "Bruant fauve", "href": "bruant.fauve" },
  { "name": "Bruant fou", "href": "bruant.fou" },
  { "name": "Bruant jaune", "href": "bruant.jaune" },
  { "name": "Bruant lapon", "href": "bruant.lapon" },
  { "name": "Bruant masqué", "href": "bruant.masque" },
  { "name": "Bruant mélanocéphale", "href": "bruant.melanocephale" },
  { "name": "Bruant nain", "href": "bruant.nain" },
  { "name": "Bruant ortolan", "href": "bruant.ortolan" },
  { "name": "Bruant proyer", "href": "bruant.proyer" },
  { "name": "Bruant roux", "href": "bruant.roux" },
  { "name": "Bruant rustique", "href": "bruant.rustique" },
  { "name": "Bruant striolé", "href": "bruant.striole" },
  { "name": "Bruant zizi", "href": "bruant.zizi" },
  { "name": "Bulbul d'Arabie", "href": "bulbul.d.arabie" },
  { "name": "Bulbul des jardins", "href": "bulbul.des.jardins" },
  { "name": "Bulbul ocré", "href": "bulbul.ocre" },
  { "name": "Busard cendré", "href": "busard.cendre" },
  { "name": "Busard d'Amérique", "href": "busard.d.amerique" },
  { "name": "Busard des roseaux", "href": "busard.des.roseaux" },
  { "name": "Busard pâle", "href": "busard.pale" },
  { "name": "Busard Saint-Martin", "href": "busard.saint-martin" },
  { "name": "Buse de Chine", "href": "buse.de.chine" },
  { "name": "Buse féroce", "href": "buse.feroce" },
  { "name": "Buse pattue", "href": "buse.pattue" },
  { "name": "Buse variable", "href": "buse.variable" },
  { "name": "Butor d'Amérique", "href": "butor.d.amerique" },
  { "name": "Butor étoilé", "href": "butor.etoile" },
  { "name": "Caille des blés", "href": "caille.des.bles" },
  { "name": "Canard à faucilles", "href": "canard.a.faucilles" },
  { "name": "Canard à front blanc", "href": "canard.a.front.blanc" },
  { "name": "Canard carolin", "href": "canard.carolin" },
  { "name": "Canard chipeau", "href": "canard.chipeau" },
  { "name": "Canard colvert", "href": "canard.colvert" },
  { "name": "Canard mandarin", "href": "canard.mandarin" },
  { "name": "Canard noir", "href": "canard.noir" },
  { "name": "Canard pilet", "href": "canard.pilet" },
  { "name": "Canard siffleur", "href": "canard.siffleur" },
  { "name": "Canard souchet", "href": "canard.souchet" },
  { "name": "Capucin bec-de-plomb", "href": "capucin.bec-de-plomb" },
  { "name": "Cardinal à poitrine rose", "href": "cardinal.a.poitrine.rose" },
  { "name": "Carouge à tête jaune", "href": "carouge.a.tete.jaune" },
  { "name": "Cassenoix moucheté", "href": "cassenoix.mouchete" },
  { "name": "Chardonneret élégant", "href": "chardonneret.elegant" },
  { "name": "Chevalier à pattes jaunes", "href": "chevalier.a.pattes.jaunes" },
  { "name": "Chevalier aboyeur", "href": "chevalier.aboyeur" },
  { "name": "Chevalier arlequin", "href": "chevalier.arlequin" },
  { "name": "Chevalier bargette", "href": "chevalier.bargette" },
  { "name": "Chevalier criard", "href": "chevalier.criard" },
  { "name": "Chevalier culblanc", "href": "chevalier.culblanc" },
  { "name": "Chevalier de Sibérie", "href": "chevalier.de.siberie" },
  { "name": "Chevalier gambette", "href": "chevalier.gambette" },
  { "name": "Chevalier grivelé", "href": "chevalier.grivele" },
  { "name": "Chevalier guignette", "href": "chevalier.guignette" },
  { "name": "Chevalier semipalmé", "href": "chevalier.semipalme" },
  { "name": "Chevalier solitaire", "href": "chevalier.solitaire" },
  { "name": "Chevalier stagnatile", "href": "chevalier.stagnatile" },
  { "name": "Chevalier sylvain", "href": "chevalier.sylvain" },
  { "name": "Chevêche d'Athéna", "href": "cheveche.d.athena" },
  { "name": "Chevêchette d'Europe", "href": "chevechette.d.europe" },
  { "name": "Chionis blanc", "href": "chionis.blanc" },
  { "name": "Chocard à bec jaune", "href": "chocard.a.bec.jaune" },
  { "name": "Choucas de Daourie", "href": "choucas.de.daourie" },
  { "name": "Choucas des tours", "href": "choucas.des.tours" },
  { "name": "Chouette de l'Oural", "href": "chouette.de.l.oural" },
  { "name": "Chouette de Tengmalm", "href": "chouette.de.tengmalm" },
  { "name": "Chouette épervière", "href": "chouette.eperviere" },
  { "name": "Chouette hulotte", "href": "chouette.hulotte" },
  { "name": "Chouette lapone", "href": "chouette.lapone" },
  { "name": "Cigogne blanche", "href": "cigogne.blanche" },
  { "name": "Cigogne épiscopale", "href": "cigogne.episcopale" },
  { "name": "Cigogne noire", "href": "cigogne.noire" },
  { "name": "Cincle plongeur", "href": "cincle.plongeur" },
  { "name": "Circaète Jean-le-Blanc", "href": "circaete.jean-le-blanc" },
  { "name": "Cisticole des joncs", "href": "cisticole.des.joncs" },
  { "name": "Cochevis de Thékla", "href": "cochevis.de.thekla" },
  { "name": "Cochevis huppé", "href": "cochevis.huppe" },
  { "name": "Colin de Californie", "href": "colin.de.californie" },
  { "name": "Colin de Virginie", "href": "colin.de.virginie" },
  { "name": "Combattant varié", "href": "combattant.varie" },
  { "name": "Conure veuve", "href": "conure.veuve" },
  { "name": "Corbeau brun", "href": "corbeau.brun" },
  { "name": "Corbeau familier", "href": "corbeau.familier" },
  { "name": "Corbeau freux", "href": "corbeau.freux" },
  { "name": "Corbeau pie", "href": "corbeau.pie" },
  { "name": "Cormoran à aigrettes", "href": "cormoran.a.aigrettes" },
  { "name": "Cormoran de Temminck", "href": "cormoran.de.temminck" },
  { "name": "Cormoran huppé", "href": "cormoran.huppe" },
  { "name": "Cormoran pélagique", "href": "cormoran.pelagique" },
  { "name": "Cormoran pygmée", "href": "cormoran.pygmee" },
  { "name": "Corneille mantelée", "href": "corneille.mantelee" },
  { "name": "Corneille noire", "href": "corneille.noire" },
  { "name": "Coucou geai", "href": "coucou.geai" },
  { "name": "Coucou gris", "href": "coucou.gris" },
  { "name": "Coucou oriental", "href": "coucou.oriental" },
  { "name": "Coulicou à bec jaune", "href": "coulicou.a.bec.jaune" },
  { "name": "Coulicou à bec noir", "href": "coulicou.a.bec.noir" },
  { "name": "Courlis à bec grêle", "href": "courlis.a.bec.grele" },
  { "name": "Courlis cendré", "href": "courlis.cendre" },
  { "name": "Courlis corlieu", "href": "courlis.corlieu" },
  { "name": "Courlis esquimau", "href": "courlis.esquimau" },
  { "name": "Courlis nain", "href": "courlis.nain" },
  { "name": "Courvite isabelle", "href": "courvite.isabelle" },
  { "name": "Crabier chevelu", "href": "crabier.chevelu" },
  { "name": "Crabier chinois", "href": "crabier.chinois" },
  { "name": "Crabier de Gray", "href": "crabier.de.gray" },
  { "name": "Crave à bec rouge", "href": "crave.a.bec.rouge" },
  { "name": "Crécerelle d'Amérique", "href": "crecerelle.d.amerique" },
  { "name": "Cygne chanteur", "href": "cygne.chanteur" },
  { "name": "Cygne de Bewick", "href": "cygne.de.bewick" },
  { "name": "Cygne noir", "href": "cygne.noir" },
  { "name": "Cygne tuberculé", "href": "cygne.tubercule" },
  { "name": "Damier du Cap", "href": "damier.du.cap" },
  { "name": "Dendrocygne fauve", "href": "dendrocygne.fauve" },
  { "name": "Dendrocygne veuf", "href": "dendrocygne.veuf" },
  { "name": "Dickcissel d'Amérique", "href": "dickcissel.d.amerique" },
  { "name": "Dindon sauvage", "href": "dindon.sauvage" },
  { "name": "Durbec des sapins", "href": "durbec.des.sapins" },
  { "name": "Échasse blanche", "href": "echasse.blanche" },
  { "name": "Effraie des clochers", "href": "effraie.des.clochers" },
  { "name": "Eider à duvet", "href": "eider.a.duvet" },
  { "name": "Eider à lunettes", "href": "eider.a.lunettes" },
  { "name": "Eider à tête grise", "href": "eider.a.tete.grise" },
  { "name": "Eider de Steller", "href": "eider.de.steller" },
  { "name": "Élanion blanc", "href": "elanion.blanc" },
  {
    "name": "Engoulevent à collier roux",
    "href": "engoulevent.a.collier.roux"
  },
  { "name": "Engoulevent d'Amérique", "href": "engoulevent.d.amerique" },
  { "name": "Engoulevent d'Europe", "href": "engoulevent.d.europe" },
  { "name": "Engoulevent du désert", "href": "engoulevent.du.desert" },
  { "name": "Épervier à pieds courts", "href": "epervier.a.pieds.courts" },
  { "name": "Épervier d'Europe", "href": "epervier.d.europe" },
  { "name": "Épervier du Japon", "href": "epervier.du.japon" },
  { "name": "Épervier shikra", "href": "epervier.shikra" },
  { "name": "Érismature à tête blanche", "href": "erismature.a.tete.blanche" },
  { "name": "Érismature rousse", "href": "erismature.rousse" },
  { "name": "Étourneau de Daourie", "href": "etourneau.de.daourie" },
  { "name": "Étourneau roselin", "href": "etourneau.roselin" },
  { "name": "Étourneau sansonnet", "href": "etourneau.sansonnet" },
  { "name": "Étourneau unicolore", "href": "etourneau.unicolore" },
  { "name": "Euplecte monseigneur", "href": "euplecte.monseigneur" },
  { "name": "Euplecte vorabé", "href": "euplecte.vorabe" },
  { "name": "Faisan de Colchide", "href": "faisan.de.colchide" },
  { "name": "Faisan de Lady Amherst", "href": "faisan.de.lady.amherst" },
  { "name": "Faisan doré", "href": "faisan.dore" },
  { "name": "Faisan vénéré", "href": "faisan.venere" },
  { "name": "Faucon concolore", "href": "faucon.concolore" },
  { "name": "Faucon crécerelle", "href": "faucon.crecerelle" },
  { "name": "Faucon crécerellette", "href": "faucon.crecerellette" },
  { "name": "Faucon d'Éléonore", "href": "faucon.d.eleonore" },
  { "name": "Faucon de l'Amour", "href": "faucon.de.l.amour" },
  { "name": "Faucon émerillon", "href": "faucon.emerillon" },
  { "name": "Faucon gerfaut", "href": "faucon.gerfaut" },
  { "name": "Faucon hobereau", "href": "faucon.hobereau" },
  { "name": "Faucon kobez", "href": "faucon.kobez" },
  { "name": "Faucon lanier", "href": "faucon.lanier" },
  { "name": "Faucon pèlerin", "href": "faucon.pelerin" },
  { "name": "Faucon sacre", "href": "faucon.sacre" },
  { "name": "Fauvette à lunettes", "href": "fauvette.a.lunettes" },
  { "name": "Fauvette à tête noire", "href": "fauvette.a.tete.noire" },
  { "name": "Fauvette babillarde", "href": "fauvette.babillarde" },
  { "name": "Fauvette de Chypre", "href": "fauvette.de.chypre" },
  { "name": "Fauvette de l'Atlas", "href": "fauvette.de.l.atlas" },
  { "name": "Fauvette de Ménétries", "href": "fauvette.de.menetries" },
  { "name": "Fauvette de Moltoni", "href": "fauvette.de.moltoni" },
  { "name": "Fauvette de Rüppell", "href": "fauvette.de.ruppell" },
  { "name": "Fauvette des Baléares", "href": "fauvette.des.baleares" },
  { "name": "Fauvette des jardins", "href": "fauvette.des.jardins" },
  { "name": "Fauvette du désert", "href": "fauvette.du.desert" },
  { "name": "Fauvette épervière", "href": "fauvette.eperviere" },
  { "name": "Fauvette grisette", "href": "fauvette.grisette" },
  { "name": "Fauvette mélanocéphale", "href": "fauvette.melanocephale" },
  { "name": "Fauvette naine", "href": "fauvette.naine" },
  { "name": "Fauvette orphéane", "href": "fauvette.orpheane" },
  { "name": "Fauvette orphée", "href": "fauvette.orphee" },
  { "name": "Fauvette passerinette", "href": "fauvette.passerinette" },
  { "name": "Fauvette pitchou", "href": "fauvette.pitchou" },
  { "name": "Fauvette sarde", "href": "fauvette.sarde" },
  { "name": "Flamant nain", "href": "flamant.nain" },
  { "name": "Flamant rose", "href": "flamant.rose" },
  { "name": "Fou à pieds rouges", "href": "fou.a.pieds.rouges" },
  { "name": "Fou brun", "href": "fou.brun" },
  { "name": "Fou de Bassan", "href": "fou.de.bassan" },
  { "name": "Fou du Cap", "href": "fou.du.cap" },
  { "name": "Fou masqué", "href": "fou.masque" },
  { "name": "Foulque caronculée", "href": "foulque.caronculee" },
  { "name": "Foulque d'Amérique", "href": "foulque.d.amerique" },
  { "name": "Foulque macroule", "href": "foulque.macroule" },
  { "name": "Francolin d'Erckel", "href": "francolin.d.erckel" },
  { "name": "Francolin noir", "href": "francolin.noir" },
  { "name": "Frégate aigle-de-mer", "href": "fregate.aigle-de-mer" },
  { "name": "Frégate superbe", "href": "fregate.superbe" },
  { "name": "Fuligule à bec cerclé", "href": "fuligule.a.bec.cercle" },
  { "name": "Fuligule à dos blanc", "href": "fuligule.a.dos.blanc" },
  { "name": "Fuligule à tête noire", "href": "fuligule.a.tete.noire" },
  { "name": "Fuligule à tête rouge", "href": "fuligule.a.tete.rouge" },
  { "name": "Fuligule milouin", "href": "fuligule.milouin" },
  { "name": "Fuligule milouinan", "href": "fuligule.milouinan" },
  { "name": "Fuligule morillon", "href": "fuligule.morillon" },
  { "name": "Fuligule nyroca", "href": "fuligule.nyroca" },
  { "name": "Fulmar boréal", "href": "fulmar.boreal" },
  { "name": "Gallinule africaine", "href": "gallinule.africaine" },
  { "name": "Gallinule d'Amérique", "href": "gallinule.d.amerique" },
  { "name": "Gallinule poule-d'eau", "href": "gallinule.poule-d.eau" },
  { "name": "Ganga à ventre brun", "href": "ganga.a.ventre.brun" },
  { "name": "Ganga cata", "href": "ganga.cata" },
  { "name": "Ganga quadribande", "href": "ganga.quadribande" },
  { "name": "Ganga tacheté", "href": "ganga.tachete" },
  { "name": "Ganga unibande", "href": "ganga.unibande" },
  { "name": "Garde-boeufs d'Asie", "href": "garde-boeufs.d.asie" },
  { "name": "Garrot à oeil d'or", "href": "garrot.a.oeil.d.or" },
  { "name": "Garrot albéole", "href": "garrot.albeole" },
  { "name": "Garrot d'Islande", "href": "garrot.d.islande" },
  { "name": "Geai des chênes", "href": "geai.des.chenes" },
  { "name": "Gélinotte des bois", "href": "gelinotte.des.bois" },
  { "name": "Glaréole à ailes noires", "href": "glareole.a.ailes.noires" },
  { "name": "Glaréole à collier", "href": "glareole.a.collier" },
  { "name": "Glaréole orientale", "href": "glareole.orientale" },
  { "name": "Gobemouche à collier", "href": "gobemouche.a.collier" },
  { "name": "Gobemouche à demi-collier", "href": "gobemouche.a.demi-collier" },
  { "name": "Gobemouche brun", "href": "gobemouche.brun" },
  { "name": "Gobemouche de la taïga", "href": "gobemouche.de.la.taiga" },
  { "name": "Gobemouche de Sibérie", "href": "gobemouche.de.siberie" },
  { "name": "Gobemouche gris", "href": "gobemouche.gris" },
  { "name": "Gobemouche mugimaki", "href": "gobemouche.mugimaki" },
  { "name": "Gobemouche nain", "href": "gobemouche.nain" },
  { "name": "Gobemouche noir", "href": "gobemouche.noir" },
  { "name": "Goéland à ailes blanches", "href": "goeland.a.ailes.blanches" },
  { "name": "Goéland à ailes grises", "href": "goeland.a.ailes.grises" },
  { "name": "Goéland à bec cerclé", "href": "goeland.a.bec.cercle" },
  { "name": "Goéland à iris blanc", "href": "goeland.a.iris.blanc" },
  { "name": "Goéland à manteau ardoisé", "href": "goeland.a.manteau.ardoise" },
  { "name": "Goéland argenté", "href": "goeland.argente" },
  { "name": "Goéland bourgmestre", "href": "goeland.bourgmestre" },
  { "name": "Goéland brun", "href": "goeland.brun" },
  { "name": "Goéland cendré", "href": "goeland.cendre" },
  { "name": "Goéland d'Amérique", "href": "goeland.d.amerique" },
  { "name": "Goéland d'Arménie", "href": "goeland.d.armenie" },
  { "name": "Goéland d'Audouin", "href": "goeland.d.audouin" },
  { "name": "Goéland dominicain", "href": "goeland.dominicain" },
  { "name": "Goéland ichthyaète", "href": "goeland.ichthyaete" },
  { "name": "Goéland leucophée", "href": "goeland.leucophee" },
  { "name": "Goéland marin", "href": "goeland.marin" },
  { "name": "Goéland pontique", "href": "goeland.pontique" },
  { "name": "Goéland railleur", "href": "goeland.railleur" },
  { "name": "Goglu des prés", "href": "goglu.des.pres" },
  { "name": "Gorgebleue à miroir", "href": "gorgebleue.a.miroir" },
  { "name": "Grand-duc d'Europe", "href": "grand-duc.d.europe" },
  { "name": "Grand Corbeau", "href": "grand.corbeau" },
  { "name": "Grand Cormoran", "href": "grand.cormoran" },
  { "name": "Grand Gravelot", "href": "grand.gravelot" },
  { "name": "Grand Héron", "href": "grand.heron" },
  { "name": "Grand Labbe", "href": "grand.labbe" },
  { "name": "Grand Tétras", "href": "grand.tetras" },
  { "name": "Grande Aigrette", "href": "grande.aigrette" },
  {
    "name": "Gravelot à collier interrompu",
    "href": "gravelot.a.collier.interrompu"
  },
  { "name": "Gravelot de Leschenault", "href": "gravelot.de.leschenault" },
  { "name": "Gravelot kildir", "href": "gravelot.kildir" },
  { "name": "Gravelot mongol", "href": "gravelot.mongol" },
  { "name": "Gravelot oriental", "href": "gravelot.oriental" },
  { "name": "Gravelot pâtre", "href": "gravelot.patre" },
  { "name": "Gravelot semipalmé", "href": "gravelot.semipalme" },
  { "name": "Grèbe à bec bigarré", "href": "grebe.a.bec.bigarre" },
  { "name": "Grèbe à cou noir", "href": "grebe.a.cou.noir" },
  { "name": "Grèbe castagneux", "href": "grebe.castagneux" },
  { "name": "Grèbe esclavon", "href": "grebe.esclavon" },
  { "name": "Grèbe huppé", "href": "grebe.huppe" },
  { "name": "Grèbe jougris", "href": "grebe.jougris" },
  { "name": "Grimpereau des bois", "href": "grimpereau.des.bois" },
  { "name": "Grimpereau des jardins", "href": "grimpereau.des.jardins" },
  { "name": "Grive à ailes rousses", "href": "grive.a.ailes.rousses" },
  { "name": "Grive à collier", "href": "grive.a.collier" },
  { "name": "Grive à dos olive", "href": "grive.a.dos.olive" },
  { "name": "Grive à gorge noire", "href": "grive.a.gorge.noire" },
  { "name": "Grive à gorge rousse", "href": "grive.a.gorge.rousse" },
  { "name": "Grive à joues grises", "href": "grive.a.joues.grises" },
  { "name": "Grive dama", "href": "grive.dama" },
  { "name": "Grive de Bicknell", "href": "grive.de.bicknell" },
  { "name": "Grive de Naumann", "href": "grive.de.naumann" },
  { "name": "Grive de Sibérie", "href": "grive.de.siberie" },
  { "name": "Grive des bois", "href": "grive.des.bois" },
  { "name": "Grive dorée", "href": "grive.doree" },
  { "name": "Grive draine", "href": "grive.draine" },
  { "name": "Grive fauve", "href": "grive.fauve" },
  { "name": "Grive litorne", "href": "grive.litorne" },
  { "name": "Grive mauvis", "href": "grive.mauvis" },
  { "name": "Grive musicienne", "href": "grive.musicienne" },
  { "name": "Grive obscure", "href": "grive.obscure" },
  { "name": "Grive solitaire", "href": "grive.solitaire" },
  { "name": "Grosbec casse-noyaux", "href": "grosbec.casse-noyaux" },
  { "name": "Grosbec errant", "href": "grosbec.errant" },
  { "name": "Grue cendrée", "href": "grue.cendree" },
  { "name": "Grue de Sibérie", "href": "grue.de.siberie" },
  { "name": "Grue demoiselle", "href": "grue.demoiselle" },
  { "name": "Grue du Canada", "href": "grue.du.canada" },
  { "name": "Grue moine", "href": "grue.moine" },
  { "name": "Guêpier d'Europe", "href": "guepier.d.europe" },
  { "name": "Guêpier d'Orient", "href": "guepier.d.orient" },
  { "name": "Guêpier de Madagascar", "href": "guepier.de.madagascar" },
  { "name": "Guêpier de Perse", "href": "guepier.de.perse" },
  { "name": "Guifette leucoptère", "href": "guifette.leucoptere" },
  { "name": "Guifette moustac", "href": "guifette.moustac" },
  { "name": "Guifette noire", "href": "guifette.noire" },
  { "name": "Guillemot à cou blanc", "href": "guillemot.a.cou.blanc" },
  { "name": "Guillemot à long bec", "href": "guillemot.a.long.bec" },
  { "name": "Guillemot à miroir", "href": "guillemot.a.miroir" },
  { "name": "Guillemot de Brünnich", "href": "guillemot.de.brunnich" },
  { "name": "Guillemot de Troïl", "href": "guillemot.de.troil" },
  { "name": "Guiraca bleu", "href": "guiraca.bleu" },
  { "name": "Gypaète barbu", "href": "gypaete.barbu" },
  { "name": "Harelde boréale", "href": "harelde.boreale" },
  { "name": "Harfang des neiges", "href": "harfang.des.neiges" },
  { "name": "Harle bièvre", "href": "harle.bievre" },
  { "name": "Harle couronné", "href": "harle.couronne" },
  { "name": "Harle huppé", "href": "harle.huppe" },
  { "name": "Harle piette", "href": "harle.piette" },
  { "name": "Héron cendré", "href": "heron.cendre" },
  { "name": "Héron garde-boeufs", "href": "heron.garde-boeufs" },
  { "name": "Héron mélanocéphale", "href": "heron.melanocephale" },
  { "name": "Héron pourpré", "href": "heron.pourpre" },
  { "name": "Héron strié", "href": "heron.strie" },
  { "name": "Héron vert", "href": "heron.vert" },
  { "name": "Hibou des marais", "href": "hibou.des.marais" },
  { "name": "Hibou du Cap", "href": "hibou.du.cap" },
  { "name": "Hibou moyen-duc", "href": "hibou.moyen-duc" },
  { "name": "Hirondelle à front blanc", "href": "hirondelle.a.front.blanc" },
  { "name": "Hirondelle bicolore", "href": "hirondelle.bicolore" },
  { "name": "Hirondelle de fenêtre", "href": "hirondelle.de.fenetre" },
  { "name": "Hirondelle de rivage", "href": "hirondelle.de.rivage" },
  { "name": "Hirondelle de rochers", "href": "hirondelle.de.rochers" },
  { "name": "Hirondelle isabelline", "href": "hirondelle.isabelline" },
  { "name": "Hirondelle noire", "href": "hirondelle.noire" },
  { "name": "Hirondelle paludicole", "href": "hirondelle.paludicole" },
  { "name": "Hirondelle rousseline", "href": "hirondelle.rousseline" },
  { "name": "Hirondelle rustique", "href": "hirondelle.rustique" },
  { "name": "Huîtrier de Moquin", "href": "huitrier.de.moquin" },
  { "name": "Huîtrier pie", "href": "huitrier.pie" },
  { "name": "Huppe fasciée", "href": "huppe.fasciee" },
  { "name": "Hypocolius gris", "href": "hypocolius.gris" },
  { "name": "Hypolaïs bottée", "href": "hypolais.bottee" },
  { "name": "Hypolaïs d'Upcher", "href": "hypolais.d.upcher" },
  { "name": "Hypolaïs des oliviers", "href": "hypolais.des.oliviers" },
  { "name": "Hypolaïs ictérine", "href": "hypolais.icterine" },
  { "name": "Hypolaïs obscure", "href": "hypolais.obscure" },
  { "name": "Hypolaïs pâle", "href": "hypolais.pale" },
  { "name": "Hypolaïs polyglotte", "href": "hypolais.polyglotte" },
  { "name": "Hypolaïs rama", "href": "hypolais.rama" },
  { "name": "Ibis chauve", "href": "ibis.chauve" },
  { "name": "Ibis falcinelle", "href": "ibis.falcinelle" },
  { "name": "Ibis sacré", "href": "ibis.sacre" },
  { "name": "Inséparable de Fischer", "href": "inseparable.de.fischer" },
  { "name": "Inséparable masqué", "href": "inseparable.masque" },
  { "name": "Iranie à gorge blanche", "href": "iranie.a.gorge.blanche" },
  { "name": "Jaseur boréal", "href": "jaseur.boreal" },
  { "name": "Jaseur d'Amérique", "href": "jaseur.d.amerique" },
  { "name": "Junco ardoisé", "href": "junco.ardoise" },
  { "name": "Kétoupa brun", "href": "ketoupa.brun" },
  { "name": "Labbe à longue queue", "href": "labbe.a.longue.queue" },
  { "name": "Labbe de McCormick", "href": "labbe.de.mccormick" },
  { "name": "Labbe parasite", "href": "labbe.parasite" },
  { "name": "Labbe pomarin", "href": "labbe.pomarin" },
  { "name": "Lagopède alpin", "href": "lagopede.alpin" },
  { "name": "Lagopède des saules", "href": "lagopede.des.saules" },
  { "name": "Léiothrix jaune", "href": "leiothrix.jaune" },
  { "name": "Linotte à bec jaune", "href": "linotte.a.bec.jaune" },
  { "name": "Linotte mélodieuse", "href": "linotte.melodieuse" },
  { "name": "Locustelle de Pallas", "href": "locustelle.de.pallas" },
  { "name": "Locustelle de Pleske", "href": "locustelle.de.pleske" },
  { "name": "Locustelle fasciée", "href": "locustelle.fasciee" },
  { "name": "Locustelle fluviatile", "href": "locustelle.fluviatile" },
  { "name": "Locustelle lancéolée", "href": "locustelle.lanceolee" },
  { "name": "Locustelle luscinioïde", "href": "locustelle.luscinioide" },
  { "name": "Locustelle tachetée", "href": "locustelle.tachetee" },
  { "name": "Loriot d'Europe", "href": "loriot.d.europe" },
  { "name": "Lusciniole à moustaches", "href": "lusciniole.a.moustaches" },
  { "name": "Macareux huppé", "href": "macareux.huppe" },
  { "name": "Macareux moine", "href": "macareux.moine" },
  { "name": "Macareux rhinocéros", "href": "macareux.rhinoceros" },
  { "name": "Macreuse à ailes blanches", "href": "macreuse.a.ailes.blanches" },
  { "name": "Macreuse à bec jaune", "href": "macreuse.a.bec.jaune" },
  { "name": "Macreuse à front blanc", "href": "macreuse.a.front.blanc" },
  { "name": "Macreuse brune", "href": "macreuse.brune" },
  { "name": "Macreuse noire", "href": "macreuse.noire" },
  { "name": "Marabout d'Afrique", "href": "marabout.d.afrique" },
  { "name": "Marouette de Baillon", "href": "marouette.de.baillon" },
  { "name": "Marouette de Caroline", "href": "marouette.de.caroline" },
  { "name": "Marouette ponctuée", "href": "marouette.ponctuee" },
  { "name": "Marouette poussin", "href": "marouette.poussin" },
  { "name": "Marouette rayée", "href": "marouette.rayee" },
  { "name": "Martin-chasseur de Smyrne", "href": "martin-chasseur.de.smyrne" },
  { "name": "Martin-pêcheur d'Amérique", "href": "martin-pecheur.d.amerique" },
  { "name": "Martin-pêcheur d'Europe", "href": "martin-pecheur.d.europe" },
  { "name": "Martin-pêcheur pie", "href": "martin-pecheur.pie" },
  { "name": "Martin huppé", "href": "martin.huppe" },
  { "name": "Martinet à ventre blanc", "href": "martinet.a.ventre.blanc" },
  { "name": "Martinet cafre", "href": "martinet.cafre" },
  { "name": "Martinet de Sibérie", "href": "martinet.de.siberie" },
  { "name": "Martinet des maisons", "href": "martinet.des.maisons" },
  { "name": "Martinet épineux", "href": "martinet.epineux" },
  { "name": "Martinet noir", "href": "martinet.noir" },
  { "name": "Martinet pâle", "href": "martinet.pale" },
  { "name": "Martinet ramoneur", "href": "martinet.ramoneur" },
  { "name": "Martinet unicolore", "href": "martinet.unicolore" },
  { "name": "Mergule nain", "href": "mergule.nain" },
  { "name": "Merle à plastron", "href": "merle.a.plastron" },
  { "name": "Merle d'Amérique", "href": "merle.d.amerique" },
  { "name": "Merle noir", "href": "merle.noir" },
  { "name": "Merle unicolore", "href": "merle.unicolore" },
  { "name": "Mésange azurée", "href": "mesange.azuree" },
  { "name": "Mésange bleue", "href": "mesange.bleue" },
  { "name": "Mésange boréale", "href": "mesange.boreale" },
  { "name": "Mésange charbonnière", "href": "mesange.charbonniere" },
  { "name": "Mésange huppée", "href": "mesange.huppee" },
  { "name": "Mésange lapone", "href": "mesange.lapone" },
  { "name": "Mésange lugubre", "href": "mesange.lugubre" },
  { "name": "Mésange noire", "href": "mesange.noire" },
  { "name": "Mésange nonnette", "href": "mesange.nonnette" },
  { "name": "Mésange nord-africaine", "href": "mesange.nord-africaine" },
  { "name": "Mésangeai imitateur", "href": "mesangeai.imitateur" },
  { "name": "Milan à queue fourchue", "href": "milan.a.queue.fourchue" },
  { "name": "Milan noir", "href": "milan.noir" },
  { "name": "Milan royal", "href": "milan.royal" },
  { "name": "Moineau à gorge jaune", "href": "moineau.a.gorge.jaune" },
  { "name": "Moineau cisalpin", "href": "moineau.cisalpin" },
  { "name": "Moineau de la mer Morte", "href": "moineau.de.la.mer.morte" },
  { "name": "Moineau des saxaouls", "href": "moineau.des.saxaouls" },
  { "name": "Moineau domestique", "href": "moineau.domestique" },
  { "name": "Moineau espagnol", "href": "moineau.espagnol" },
  { "name": "Moineau friquet", "href": "moineau.friquet" },
  { "name": "Moineau pâle", "href": "moineau.pale" },
  { "name": "Moineau soulcie", "href": "moineau.soulcie" },
  { "name": "Moinelette à front blanc", "href": "moinelette.a.front.blanc" },
  { "name": "Monticole bleu", "href": "monticole.bleu" },
  { "name": "Monticole de roche", "href": "monticole.de.roche" },
  { "name": "Moqueur chat", "href": "moqueur.chat" },
  { "name": "Moqueur polyglotte", "href": "moqueur.polyglotte" },
  { "name": "Moqueur roux", "href": "moqueur.roux" },
  { "name": "Moucherolle à côtés olive", "href": "moucherolle.a.cotes.olive" },
  {
    "name": "Moucherolle à ventre jaune",
    "href": "moucherolle.a.ventre.jaune"
  },
  { "name": "Moucherolle des aulnes", "href": "moucherolle.des.aulnes" },
  { "name": "Moucherolle phébi", "href": "moucherolle.phebi" },
  { "name": "Moucherolle tchébec", "href": "moucherolle.tchebec" },
  { "name": "Moucherolle vert", "href": "moucherolle.vert" },
  { "name": "Mouette à tête grise", "href": "mouette.a.tete.grise" },
  { "name": "Mouette atricille", "href": "mouette.atricille" },
  { "name": "Mouette blanche", "href": "mouette.blanche" },
  { "name": "Mouette de Bonaparte", "href": "mouette.de.bonaparte" },
  { "name": "Mouette de Franklin", "href": "mouette.de.franklin" },
  { "name": "Mouette de Ross", "href": "mouette.de.ross" },
  { "name": "Mouette de Sabine", "href": "mouette.de.sabine" },
  { "name": "Mouette mélanocéphale", "href": "mouette.melanocephale" },
  { "name": "Mouette pygmée", "href": "mouette.pygmee" },
  { "name": "Mouette relique", "href": "mouette.relique" },
  { "name": "Mouette rieuse", "href": "mouette.rieuse" },
  { "name": "Mouette tridactyle", "href": "mouette.tridactyle" },
  { "name": "Nette rousse", "href": "nette.rousse" },
  { "name": "Niverolle alpine", "href": "niverolle.alpine" },
  { "name": "Niverolle de David", "href": "niverolle.de.david" },
  { "name": "Noddi brun", "href": "noddi.brun" },
  { "name": "Océanite culblanc", "href": "oceanite.culblanc" },
  { "name": "Océanite de Castro", "href": "oceanite.de.castro" },
  { "name": "Océanite de Monteiro", "href": "oceanite.de.monteiro" },
  { "name": "Océanite de Swinhoe", "href": "oceanite.de.swinhoe" },
  { "name": "Océanite de Wilson", "href": "oceanite.de.wilson" },
  { "name": "Océanite frégate", "href": "oceanite.fregate" },
  { "name": "Océanite tempête", "href": "oceanite.tempete" },
  { "name": "Oedicnème criard", "href": "oedicneme.criard" },
  { "name": "Oedicnème du Sénégal", "href": "oedicneme.du.senegal" },
  { "name": "Oie à bec court", "href": "oie.a.bec.court" },
  { "name": "Oie à tête barrée", "href": "oie.a.tete.barree" },
  { "name": "Oie cendrée", "href": "oie.cendree" },
  { "name": "Oie de la toundra", "href": "oie.de.la.toundra" },
  { "name": "Oie de Ross", "href": "oie.de.ross" },
  { "name": "Oie des moissons", "href": "oie.des.moissons" },
  { "name": "Oie des neiges", "href": "oie.des.neiges" },
  { "name": "Oie empereur", "href": "oie.empereur" },
  { "name": "Oie naine", "href": "oie.naine" },
  { "name": "Oie rieuse", "href": "oie.rieuse" },
  { "name": "Oriole du Nord", "href": "oriole.du.nord" },
  { "name": "Orite à longue queue", "href": "orite.a.longue.queue" },
  { "name": "Ouette d'Égypte", "href": "ouette.d.egypte" },
  { "name": "Outarde barbue", "href": "outarde.barbue" },
  { "name": "Outarde canepetière", "href": "outarde.canepetiere" },
  { "name": "Outarde de Macqueen", "href": "outarde.de.macqueen" },
  { "name": "Outarde houbara", "href": "outarde.houbara" },
  { "name": "Panure à moustaches", "href": "panure.a.moustaches" },
  {
    "name": "Paradoxornis à gorge cendrée",
    "href": "paradoxornis.a.gorge.cendree"
  },
  { "name": "Paruline à ailes bleues", "href": "paruline.a.ailes.bleues" },
  { "name": "Paruline à ailes dorées", "href": "paruline.a.ailes.dorees" },
  { "name": "Paruline à calotte noire", "href": "paruline.a.calotte.noire" },
  { "name": "Paruline à capuchon", "href": "paruline.a.capuchon" },
  { "name": "Paruline à collier", "href": "paruline.a.collier" },
  {
    "name": "Paruline à couronne rousse",
    "href": "paruline.a.couronne.rousse"
  },
  { "name": "Paruline à croupion jaune", "href": "paruline.a.croupion.jaune" },
  { "name": "Paruline à flancs marron", "href": "paruline.a.flancs.marron" },
  { "name": "Paruline à gorge noire", "href": "paruline.a.gorge.noire" },
  { "name": "Paruline à gorge orangée", "href": "paruline.a.gorge.orangee" },
  { "name": "Paruline à joues grises", "href": "paruline.a.joues.grises" },
  { "name": "Paruline à poitrine baie", "href": "paruline.a.poitrine.baie" },
  { "name": "Paruline à tête cendrée", "href": "paruline.a.tete.cendree" },
  { "name": "Paruline azurée", "href": "paruline.azuree" },
  { "name": "Paruline bleue", "href": "paruline.bleue" },
  { "name": "Paruline couronnée", "href": "paruline.couronnee" },
  { "name": "Paruline des pins", "href": "paruline.des.pins" },
  { "name": "Paruline des ruisseaux", "href": "paruline.des.ruisseaux" },
  { "name": "Paruline du Canada", "href": "paruline.du.canada" },
  { "name": "Paruline flamboyante", "href": "paruline.flamboyante" },
  { "name": "Paruline hochequeue", "href": "paruline.hochequeue" },
  { "name": "Paruline jaune", "href": "paruline.jaune" },
  {
    "name": "Paruline jaune - groupe aestiva",
    "href": "paruline.jaune.-.groupe.aestiva"
  },
  { "name": "Paruline masquée", "href": "paruline.masquee" },
  { "name": "Paruline noir et blanc", "href": "paruline.noir.et.blanc" },
  { "name": "Paruline obscure", "href": "paruline.obscure" },
  { "name": "Paruline polyglotte", "href": "paruline.polyglotte" },
  { "name": "Paruline rayée", "href": "paruline.rayee" },
  { "name": "Paruline tigrée", "href": "paruline.tigree" },
  { "name": "Paruline triste", "href": "paruline.triste" },
  { "name": "Paruline verdâtre", "href": "paruline.verdatre" },
  { "name": "Passerin azuré", "href": "passerin.azure" },
  { "name": "Passerin indigo", "href": "passerin.indigo" },
  { "name": "Pélican blanc", "href": "pelican.blanc" },
  { "name": "Pélican frisé", "href": "pelican.frise" },
  { "name": "Pélican gris", "href": "pelican.gris" },
  { "name": "Perdrix bartavelle", "href": "perdrix.bartavelle" },
  { "name": "Perdrix choukar", "href": "perdrix.choukar" },
  { "name": "Perdrix de Daourie", "href": "perdrix.de.daourie" },
  { "name": "Perdrix gambra", "href": "perdrix.gambra" },
  { "name": "Perdrix grise", "href": "perdrix.grise" },
  { "name": "Perdrix rouge", "href": "perdrix.rouge" },
  { "name": "Perdrix si-si", "href": "perdrix.si-si" },
  { "name": "Perruche à collier", "href": "perruche.a.collier" },
  { "name": "Perruche alexandre", "href": "perruche.alexandre" },
  { "name": "Perruche ondulée", "href": "perruche.ondulee" },
  { "name": "Petit-duc de Bruce", "href": "petit-duc.de.bruce" },
  { "name": "Petit-duc scops", "href": "petit-duc.scops" },
  { "name": "Petit Blongios", "href": "petit.blongios" },
  { "name": "Petit Gravelot", "href": "petit.gravelot" },
  { "name": "Petit Puffin", "href": "petit.puffin" },
  { "name": "Petite Sterne", "href": "petite.sterne" },
  { "name": "Pétrel de Bulwer", "href": "petrel.de.bulwer" },
  { "name": "Pétrel de Hall", "href": "petrel.de.hall" },
  { "name": "Pétrel de Jouanin", "href": "petrel.de.jouanin" },
  { "name": "Pétrel de la Trinité", "href": "petrel.de.la.trinite" },
  { "name": "Pétrel de Madère", "href": "petrel.de.madere" },
  { "name": "Pétrel de Schlegel", "href": "petrel.de.schlegel" },
  { "name": "Pétrel des Bermudes", "href": "petrel.des.bermudes" },
  { "name": "Pétrel diablotin", "href": "petrel.diablotin" },
  { "name": "Pétrel géant", "href": "petrel.geant" },
  { "name": "Pétrel gongon", "href": "petrel.gongon" },
  { "name": "Pétrel hérault", "href": "petrel.herault" },
  { "name": "Pétrel soyeux", "href": "petrel.soyeux" },
  { "name": "Phaéton à bec rouge", "href": "phaeton.a.bec.rouge" },
  { "name": "Phalarope à bec étroit", "href": "phalarope.a.bec.etroit" },
  { "name": "Phalarope à bec large", "href": "phalarope.a.bec.large" },
  { "name": "Phalarope de Wilson", "href": "phalarope.de.wilson" },
  { "name": "Phragmite aquatique", "href": "phragmite.aquatique" },
  { "name": "Phragmite des joncs", "href": "phragmite.des.joncs" },
  { "name": "Pic à dos blanc", "href": "pic.a.dos.blanc" },
  { "name": "Pic cendré", "href": "pic.cendre" },
  { "name": "Pic de Sharpe", "href": "pic.de.sharpe" },
  { "name": "Pic épeiche", "href": "pic.epeiche" },
  { "name": "Pic épeichette", "href": "pic.epeichette" },
  { "name": "Pic flamboyant", "href": "pic.flamboyant" },
  { "name": "Pic maculé", "href": "pic.macule" },
  { "name": "Pic mar", "href": "pic.mar" },
  { "name": "Pic noir", "href": "pic.noir" },
  { "name": "Pic spodocéphale", "href": "pic.spodocephale" },
  { "name": "Pic syriaque", "href": "pic.syriaque" },
  { "name": "Pic tridactyle", "href": "pic.tridactyle" },
  { "name": "Pic vert", "href": "pic.vert" },
  {
    "name": "Pie-grièche à poitrine rose",
    "href": "pie-grieche.a.poitrine.rose"
  },
  { "name": "Pie-grièche à tête rousse", "href": "pie-grieche.a.tete.rousse" },
  { "name": "Pie-grièche brune", "href": "pie-grieche.brune" },
  { "name": "Pie-grièche du Turkestan", "href": "pie-grieche.du.turkestan" },
  { "name": "Pie-grièche écorcheur", "href": "pie-grieche.ecorcheur" },
  { "name": "Pie-grièche grise", "href": "pie-grieche.grise" },
  { "name": "Pie-grièche isabelle", "href": "pie-grieche.isabelle" },
  { "name": "Pie-grièche masquée", "href": "pie-grieche.masquee" },
  { "name": "Pie-grièche méridionale", "href": "pie-grieche.meridionale" },
  { "name": "Pie-grièche schach", "href": "pie-grieche.schach" },
  { "name": "Pie bavarde", "href": "pie.bavarde" },
  { "name": "Pie ibérique", "href": "pie.iberique" },
  { "name": "Pigeon biset", "href": "pigeon.biset" },
  { "name": "Pigeon colombin", "href": "pigeon.colombin" },
  { "name": "Pigeon d'Eversmann", "href": "pigeon.d.eversmann" },
  { "name": "Pigeon de Bolle", "href": "pigeon.de.bolle" },
  { "name": "Pigeon des lauriers", "href": "pigeon.des.lauriers" },
  { "name": "Pigeon des rochers", "href": "pigeon.des.rochers" },
  { "name": "Pigeon ramier", "href": "pigeon.ramier" },
  { "name": "Pigeon trocaz", "href": "pigeon.trocaz" },
  { "name": "Pingouin torda", "href": "pingouin.torda" },
  { "name": "Pinson bleu", "href": "pinson.bleu" },
  { "name": "Pinson des arbres", "href": "pinson.des.arbres" },
  { "name": "Pinson du Nord", "href": "pinson.du.nord" },
  { "name": "Pintade de Numidie", "href": "pintade.de.numidie" },
  { "name": "Pipit à dos olive", "href": "pipit.a.dos.olive" },
  { "name": "Pipit à gorge rousse", "href": "pipit.a.gorge.rousse" },
  { "name": "Pipit à long bec", "href": "pipit.a.long.bec" },
  { "name": "Pipit de Berthelot", "href": "pipit.de.berthelot" },
  { "name": "Pipit de Godlewski", "href": "pipit.de.godlewski" },
  { "name": "Pipit de la Petchora", "href": "pipit.de.la.petchora" },
  { "name": "Pipit de Richard", "href": "pipit.de.richard" },
  { "name": "Pipit des arbres", "href": "pipit.des.arbres" },
  { "name": "Pipit farlousane", "href": "pipit.farlousane" },
  { "name": "Pipit farlouse", "href": "pipit.farlouse" },
  { "name": "Pipit maritime", "href": "pipit.maritime" },
  { "name": "Pipit rousseline", "href": "pipit.rousseline" },
  { "name": "Pipit spioncelle", "href": "pipit.spioncelle" },
  { "name": "Plongeon à bec blanc", "href": "plongeon.a.bec.blanc" },
  { "name": "Plongeon arctique", "href": "plongeon.arctique" },
  { "name": "Plongeon catmarin", "href": "plongeon.catmarin" },
  { "name": "Plongeon du Pacifique", "href": "plongeon.du.pacifique" },
  { "name": "Plongeon imbrin", "href": "plongeon.imbrin" },
  { "name": "Pluvian fluviatile", "href": "pluvian.fluviatile" },
  { "name": "Pluvier argenté", "href": "pluvier.argente" },
  { "name": "Pluvier asiatique", "href": "pluvier.asiatique" },
  { "name": "Pluvier bronzé", "href": "pluvier.bronze" },
  { "name": "Pluvier doré", "href": "pluvier.dore" },
  { "name": "Pluvier fauve", "href": "pluvier.fauve" },
  { "name": "Pluvier guignard", "href": "pluvier.guignard" },
  { "name": "Pouillot à deux barres", "href": "pouillot.a.deux.barres" },
  {
    "name": "Pouillot à grands sourcils",
    "href": "pouillot.a.grands.sourcils"
  },
  { "name": "Pouillot boréal", "href": "pouillot.boreal" },
  { "name": "Pouillot brun", "href": "pouillot.brun" },
  { "name": "Pouillot de Bonelli", "href": "pouillot.de.bonelli" },
  { "name": "Pouillot de Hume", "href": "pouillot.de.hume" },
  { "name": "Pouillot de Pallas", "href": "pouillot.de.pallas" },
  { "name": "Pouillot de Schwarz", "href": "pouillot.de.schwarz" },
  { "name": "Pouillot de Temminck", "href": "pouillot.de.temminck" },
  { "name": "Pouillot des Canaries", "href": "pouillot.des.canaries" },
  { "name": "Pouillot du Caucase", "href": "pouillot.du.caucase" },
  { "name": "Pouillot fitis", "href": "pouillot.fitis" },
  { "name": "Pouillot griséole", "href": "pouillot.griseole" },
  { "name": "Pouillot ibérique", "href": "pouillot.iberique" },
  { "name": "Pouillot modeste", "href": "pouillot.modeste" },
  { "name": "Pouillot montagnard", "href": "pouillot.montagnard" },
  { "name": "Pouillot oriental", "href": "pouillot.oriental" },
  { "name": "Pouillot siffleur", "href": "pouillot.siffleur" },
  { "name": "Pouillot véloce", "href": "pouillot.veloce" },
  { "name": "Pouillot verdâtre", "href": "pouillot.verdatre" },
  { "name": "Prinia gracile", "href": "prinia.gracile" },
  { "name": "Puffin d'Audubon", "href": "puffin.d.audubon" },
  { "name": "Puffin de Buller", "href": "puffin.de.buller" },
  { "name": "Puffin de Macaronésie", "href": "puffin.de.macaronesie" },
  { "name": "Puffin de Scopoli", "href": "puffin.de.scopoli" },
  { "name": "Puffin des Anglais", "href": "puffin.des.anglais" },
  { "name": "Puffin des Baléares", "href": "puffin.des.baleares" },
  { "name": "Puffin du Cap-Vert", "href": "puffin.du.cap-vert" },
  { "name": "Puffin fuligineux", "href": "puffin.fuligineux" },
  { "name": "Puffin majeur", "href": "puffin.majeur" },
  { "name": "Puffin yelkouan", "href": "puffin.yelkouan" },
  { "name": "Pygargue à queue blanche", "href": "pygargue.a.queue.blanche" },
  { "name": "Pygargue à tête blanche", "href": "pygargue.a.tete.blanche" },
  { "name": "Pygargue de Pallas", "href": "pygargue.de.pallas" },
  { "name": "Pygargue de Steller", "href": "pygargue.de.steller" },
  { "name": "Quiscale rouilleux", "href": "quiscale.rouilleux" },
  { "name": "Râle à bec jaune", "href": "rale.a.bec.jaune" },
  { "name": "Râle d'eau", "href": "rale.d.eau" },
  { "name": "Râle de Virginie", "href": "rale.de.virginie" },
  { "name": "Râle des genêts", "href": "rale.des.genets" },
  { "name": "Râle des prés", "href": "rale.des.pres" },
  { "name": "Rémiz couronnée", "href": "remiz.couronnee" },
  { "name": "Rémiz penduline", "href": "remiz.penduline" },
  { "name": "Robin à flancs roux", "href": "robin.a.flancs.roux" },
  { "name": "Roitelet à couronne rubis", "href": "roitelet.a.couronne.rubis" },
  { "name": "Roitelet de Madère", "href": "roitelet.de.madere" },
  { "name": "Roitelet huppé", "href": "roitelet.huppe" },
  { "name": "Roitelet triple-bandeau", "href": "roitelet.triple-bandeau" },
  { "name": "Rollier d'Europe", "href": "rollier.d.europe" },
  { "name": "Rollier indien", "href": "rollier.indien" },
  { "name": "Roselin à longue queue", "href": "roselin.a.longue.queue" },
  { "name": "Roselin brun", "href": "roselin.brun" },
  { "name": "Roselin cramoisi", "href": "roselin.cramoisi" },
  { "name": "Roselin de Brandt", "href": "roselin.de.brandt" },
  { "name": "Roselin de Hodgson", "href": "roselin.de.hodgson" },
  { "name": "Roselin de Lichtenstein", "href": "roselin.de.lichtenstein" },
  { "name": "Roselin de Mongolie", "href": "roselin.de.mongolie" },
  { "name": "Roselin githagine", "href": "roselin.githagine" },
  { "name": "Roselin rose", "href": "roselin.rose" },
  { "name": "Roselin tacheté", "href": "roselin.tachete" },
  { "name": "Rossignol bleu", "href": "rossignol.bleu" },
  { "name": "Rossignol philomèle", "href": "rossignol.philomele" },
  { "name": "Rossignol progné", "href": "rossignol.progne" },
  { "name": "Rossignol siffleur", "href": "rossignol.siffleur" },
  { "name": "Rougegorge familier", "href": "rougegorge.familier" },
  { "name": "Rougequeue à front blanc", "href": "rougequeue.a.front.blanc" },
  { "name": "Rougequeue aurore", "href": "rougequeue.aurore" },
  { "name": "Rougequeue d'Eversmann", "href": "rougequeue.d.eversmann" },
  { "name": "Rougequeue de Güldenstädt", "href": "rougequeue.de.guldenstadt" },
  { "name": "Rougequeue de Moussier", "href": "rougequeue.de.moussier" },
  { "name": "Rougequeue noir", "href": "rougequeue.noir" },
  { "name": "Rousserolle à gros bec", "href": "rousserolle.a.gros.bec" },
  { "name": "Rousserolle d'Irak", "href": "rousserolle.d.irak" },
  { "name": "Rousserolle de Schrenck", "href": "rousserolle.de.schrenck" },
  { "name": "Rousserolle des buissons", "href": "rousserolle.des.buissons" },
  { "name": "Rousserolle effarvatte", "href": "rousserolle.effarvatte" },
  { "name": "Rousserolle isabelle", "href": "rousserolle.isabelle" },
  { "name": "Rousserolle stentor", "href": "rousserolle.stentor" },
  { "name": "Rousserolle turdoïde", "href": "rousserolle.turdoide" },
  { "name": "Rousserolle verderolle", "href": "rousserolle.verderolle" },
  { "name": "Sarcelle à ailes bleues", "href": "sarcelle.a.ailes.bleues" },
  { "name": "Sarcelle à ailes vertes", "href": "sarcelle.a.ailes.vertes" },
  { "name": "Sarcelle cannelle", "href": "sarcelle.cannelle" },
  { "name": "Sarcelle d'été", "href": "sarcelle.d.ete" },
  { "name": "Sarcelle d'hiver", "href": "sarcelle.d.hiver" },
  { "name": "Sarcelle élégante", "href": "sarcelle.elegante" },
  { "name": "Sarcelle marbrée", "href": "sarcelle.marbree" },
  { "name": "Serin à front rouge", "href": "serin.a.front.rouge" },
  { "name": "Serin cini", "href": "serin.cini" },
  { "name": "Serin des Canaries", "href": "serin.des.canaries" },
  { "name": "Sirli de Dupont", "href": "sirli.de.dupont" },
  { "name": "Sirli du désert", "href": "sirli.du.desert" },
  {
    "name": "Sittelle à poitrine rousse",
    "href": "sittelle.a.poitrine.rousse"
  },
  { "name": "Sittelle corse", "href": "sittelle.corse" },
  { "name": "Sittelle de Krüper", "href": "sittelle.de.kruper" },
  { "name": "Sittelle de Neumayer", "href": "sittelle.de.neumayer" },
  { "name": "Sittelle torchepot", "href": "sittelle.torchepot" },
  { "name": "Sizerin blanchâtre", "href": "sizerin.blanchatre" },
  { "name": "Sizerin cabaret", "href": "sizerin.cabaret" },
  { "name": "Sizerin flammé", "href": "sizerin.flamme" },
  { "name": "Spatule blanche", "href": "spatule.blanche" },
  { "name": "Spatule d'Afrique", "href": "spatule.d.afrique" },
  { "name": "Starique cristatelle", "href": "starique.cristatelle" },
  { "name": "Starique perroquet", "href": "starique.perroquet" },
  { "name": "Sterne arctique", "href": "sterne.arctique" },
  { "name": "Sterne bridée", "href": "sterne.bridee" },
  { "name": "Sterne caspienne", "href": "sterne.caspienne" },
  { "name": "Sterne caugek", "href": "sterne.caugek" },
  { "name": "Sterne de Cabot", "href": "sterne.de.cabot" },
  { "name": "Sterne de Dougall", "href": "sterne.de.dougall" },
  { "name": "Sterne de Forster", "href": "sterne.de.forster" },
  { "name": "Sterne de Saunders", "href": "sterne.de.saunders" },
  { "name": "Sterne des Aléoutiennes", "href": "sterne.des.aleoutiennes" },
  { "name": "Sterne élégante", "href": "sterne.elegante" },
  { "name": "Sterne fuligineuse", "href": "sterne.fuligineuse" },
  { "name": "Sterne hansel", "href": "sterne.hansel" },
  { "name": "Sterne naine", "href": "sterne.naine" },
  { "name": "Sterne pierregarin", "href": "sterne.pierregarin" },
  { "name": "Sterne royale", "href": "sterne.royale" },
  { "name": "Sterne voyageuse", "href": "sterne.voyageuse" },
  { "name": "Sturnelle des prés", "href": "sturnelle.des.pres" },
  { "name": "Syrrhapte paradoxal", "href": "syrrhapte.paradoxal" },
  { "name": "Tadorne casarca", "href": "tadorne.casarca" },
  { "name": "Tadorne de Belon", "href": "tadorne.de.belon" },
  { "name": "Talève d'Allen", "href": "taleve.d.allen" },
  { "name": "Talève sultane", "href": "taleve.sultane" },
  { "name": "Talève violacée", "href": "taleve.violacee" },
  { "name": "Tangara écarlate", "href": "tangara.ecarlate" },
  { "name": "Tangara vermillon", "href": "tangara.vermillon" },
  { "name": "Tantale ibis", "href": "tantale.ibis" },
  { "name": "Tarier de Sibérie", "href": "tarier.de.siberie" },
  { "name": "Tarier de Stejneger", "href": "tarier.de.stejneger" },
  { "name": "Tarier des Canaries", "href": "tarier.des.canaries" },
  { "name": "Tarier des prés", "href": "tarier.des.pres" },
  { "name": "Tarier pâtre", "href": "tarier.patre" },
  { "name": "Tarier pie", "href": "tarier.pie" },
  { "name": "Tarin des aulnes", "href": "tarin.des.aulnes" },
  { "name": "Tchagra à tête noire", "href": "tchagra.a.tete.noire" },
  { "name": "Tétraogalle de l'Altaï", "href": "tetraogalle.de.l.altai" },
  { "name": "Tétras à bec noir", "href": "tetras.a.bec.noir" },
  { "name": "Tétras du Caucase", "href": "tetras.du.caucase" },
  { "name": "Tétras lyre", "href": "tetras.lyre" },
  { "name": "Tichodrome échelette", "href": "tichodrome.echelette" },
  { "name": "Tisserin à tête noire", "href": "tisserin.a.tete.noire" },
  { "name": "Tisserin gendarme", "href": "tisserin.gendarme" },
  { "name": "Tisserin intermédiaire", "href": "tisserin.intermediaire" },
  { "name": "Tohi à flancs roux", "href": "tohi.a.flancs.roux" },
  { "name": "Torcol fourmilier", "href": "torcol.fourmilier" },
  { "name": "Tournepierre à collier", "href": "tournepierre.a.collier" },
  { "name": "Tourterelle des bois", "href": "tourterelle.des.bois" },
  { "name": "Tourterelle maillée", "href": "tourterelle.maillee" },
  { "name": "Tourterelle masquée", "href": "tourterelle.masquee" },
  { "name": "Tourterelle orientale", "href": "tourterelle.orientale" },
  { "name": "Tourterelle rieuse", "href": "tourterelle.rieuse" },
  { "name": "Tourterelle triste", "href": "tourterelle.triste" },
  { "name": "Tourterelle turque", "href": "tourterelle.turque" },
  { "name": "Traquet à capuchon", "href": "traquet.a.capuchon" },
  { "name": "Traquet à tête blanche", "href": "traquet.a.tete.blanche" },
  { "name": "Traquet à tête grise", "href": "traquet.a.tete.grise" },
  { "name": "Traquet de Chypre", "href": "traquet.de.chypre" },
  { "name": "Traquet de Finsch", "href": "traquet.de.finsch" },
  { "name": "Traquet deuil", "href": "traquet.deuil" },
  { "name": "Traquet du désert", "href": "traquet.du.desert" },
  { "name": "Traquet isabelle", "href": "traquet.isabelle" },
  { "name": "Traquet kurde", "href": "traquet.kurde" },
  { "name": "Traquet motteux", "href": "traquet.motteux" },
  { "name": "Traquet oreillard", "href": "traquet.oreillard" },
  { "name": "Traquet pie", "href": "traquet.pie" },
  { "name": "Traquet rieur", "href": "traquet.rieur" },
  { "name": "Travailleur à bec rouge", "href": "travailleur.a.bec.rouge" },
  { "name": "Travailleur à tête rouge", "href": "travailleur.a.tete.rouge" },
  { "name": "Troglodyte des marais", "href": "troglodyte.des.marais" },
  { "name": "Troglodyte mignon", "href": "troglodyte.mignon" },
  { "name": "Turnix mugissant", "href": "turnix.mugissant" },
  { "name": "Tyran des savanes", "href": "tyran.des.savanes" },
  { "name": "Tyran tritri", "href": "tyran.tritri" },
  { "name": "Vacher à tête brune", "href": "vacher.a.tete.brune" },
  { "name": "Vanneau à queue blanche", "href": "vanneau.a.queue.blanche" },
  { "name": "Vanneau à tête noire", "href": "vanneau.a.tete.noire" },
  { "name": "Vanneau éperonné", "href": "vanneau.eperonne" },
  { "name": "Vanneau huppé", "href": "vanneau.huppe" },
  { "name": "Vanneau indien", "href": "vanneau.indien" },
  { "name": "Vanneau sociable", "href": "vanneau.sociable" },
  { "name": "Vautour africain", "href": "vautour.africain" },
  { "name": "Vautour de Rüppell", "href": "vautour.de.ruppell" },
  { "name": "Vautour fauve", "href": "vautour.fauve" },
  { "name": "Vautour moine", "href": "vautour.moine" },
  { "name": "Vautour oricou", "href": "vautour.oricou" },
  { "name": "Vautour percnoptère", "href": "vautour.percnoptere" },
  { "name": "Venturon corse", "href": "venturon.corse" },
  { "name": "Venturon montagnard", "href": "venturon.montagnard" },
  { "name": "Verdier d'Europe", "href": "verdier.d.europe" },
  { "name": "Veuve dominicaine", "href": "veuve.dominicaine" },
  { "name": "Viréo à gorge jaune", "href": "vireo.a.gorge.jaune" },
  { "name": "Viréo à oeil rouge", "href": "vireo.a.oeil.rouge" },
  { "name": "Viréo à tête bleue", "href": "vireo.a.tete.bleue" },
  { "name": "Viréo aux yeux blancs", "href": "vireo.aux.yeux.blancs" },
  { "name": "Viréo de Philadelphie", "href": "vireo.de.philadelphie" }
]
